### ISSUE TITLE
Open more docs about the analysis of bugs

### ISSUE THREAD

**Issue by timmyyuan** [system-pclub/go-concurrency-bugs#1]
Hello, I'm excited to read this empirical bug study, especially the analysis of each concurrency bug in `bug table.xlsx`. These analysis documents are easily understandable and help me a lot. However, I found that some of links in `bug table.xlsx` (commit hash) are privilege or missing (especially the non-blocking bugs). Could you share those links to open more documents? Thank you very much anyway.

**Comment by Tengfei1010** [comment]
@timmyyuan  Sure, I will open more docs to the public.

**Comment by timmyyuan** [comment]
@Tengfei1010 Thank you for your generosity.
